package org.cru.model;

import org.cru.model.map.IndexData;

import java.util.List;

/**
 * Object to hold information that comes back from OpenDQ about the match found
 * in a more easily maintainable manner
 *
 * Created by William.Randall on 6/10/14.
 */
public class SearchResponse
{
    private double score;
    private String id;
    private IndexData resultValues;
    private String type;

    public double getScore()
    {
        return score;
    }

    public void setScore(double score)
    {
        this.score = score;
    }

    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    public IndexData getResultValues()
    {
        return resultValues;
    }

    public void setResultValues(IndexData resultValues)
    {
        this.resultValues = resultValues;
    }

    public String getType()
    {
        return type;
    }

    public void setType(String type)
    {
        this.type = type;
    }

    @Override
    public boolean equals(Object objectToCompare)
    {
        if(objectToCompare == this) return true;
        if(objectToCompare == null || !(objectToCompare instanceof SearchResponse)) return false;

        IndexData resultValuesToCompare = ((SearchResponse)objectToCompare).getResultValues();

        List<String> resultValuesForEquality = resultValues.getValuesForEquality();
        List<String> resultValuesForEqualityToCompare = resultValuesToCompare.getValuesForEquality();

        if(resultValuesForEquality.size() != resultValuesForEqualityToCompare.size()) return false;

        for(int i = 0; i < resultValuesForEquality.size(); i++)
        {
            if(!resultValuesForEquality.get(i).equalsIgnoreCase(resultValuesForEqualityToCompare.get(i)))
            {
                return false;
            }
        }

        return true;
    }

    //Generated by IntelliJ
    @Override
    public int hashCode()
    {
        int result;
        long temp;
        temp = Double.doubleToLongBits(score);
        result = (int) (temp ^ (temp >>> 32));
        result = 31 * result + id.hashCode();
        result = 31 * result + resultValues.hashCode();
        return result;
    }
}
